#!/bin/sh

COMMIT=$(git rev-parse --short HEAD)
IMAGE_NAME=riff-$COMMIT

lein do clean, uberjar
mv target/riff-web.jar docker
docker build -q -rm -t $IMAGE_NAME docker
echo $IMAGE_NAME > latest_image_tag
